### ISSUE TITLE
hdf5 headers missing

### ISSUE THREAD

**Issue by nikg321** [MHKiT-Software/MHKiT-Python#303] opened 2024-04-09 09:52 UTC
### To Reproduce:
Provide a minimal working example that reproduces the error. 

**Minimal working example:** A minimal working example is a collection of source code and other data files which allow a bug or problem to be demonstrated and reproduced. The important feature of a minimal working example is that **it is as small and as simple as possible**, such that it is just sufficient to demonstrate the problem, but without any additional complexity or dependencies which will make resolution harder.

### Desktop (please complete the following information):
 - MHKiT Version: [e.g. 0.4.0]

**Comment by ssolson** [comment] 2024-04-09 13:34
Hello @nikg321 and thank you for your interest in MHKiT.

Without the additional context requested by the issue template I cannot help you. 

Please provide additional context about how the issue is occurring so that I can help you.

**Comment by ssolson** [comment] 2024-04-10 18:09
@nikg321 you said when you try to install the package you get a netCDF 4 error in your duplicate issue #305.

How are you trying to install MHKiT?

What operating system do you use?

What version of Python do you use?

**Comment by nikg321** [comment] 2024-04-10 18:35
I try using the pip install mhkit and I hot the same error by trying git
git clone,windows 64 the python version is 3.11.7 I think

Στις Τετ 10 Απρ 2024, 9:10 μ.μ. ο χρήστης ssolson ***@***.***>
έγραψε:

**Comment by ssolson** [comment] 2024-04-10 19:15
If you have cloned the repo can you try checking out the develop branch and seeing it installs correctly?

```
cd MHKiT-Python
git checkout develop
pip install -e .
```

**Comment by nikg321** [comment] 2024-04-10 19:21
Ok, I'll check it out.

Στις Τετ 10 Απρ 2024 στις 10:15 μ.μ., ο/η ssolson ***@***.***>
έγραψε:

**Comment by nikg321** [comment] 2024-04-10 19:22
Successfully installed NREL-rex-0.2.86 aiobotocore-2.5.0 aiofiles-23.2.1
aiohttp-3.8.5 aiohttp-cors-0.7.0 aioitertools-0.11.0 aiosignal-1.3.1
async-timeout-4.0.3 azure-core-1.30.1 azure-storage-blob-12.19.1
beautifulsoup4-4.12.3 botocore-1.29.76 bottleneck-1.3.8 fatpack-0.7.7
frozenlist-1.4.1 h5pyd-0.18.0 hsds-0.8.4 isodate-0.6.1 jmespath-1.0.1
joblib-1.4.0 lxml-5.2.1 mhkit-0.7.0 multidict-6.0.5 numcodecs-0.12.1
patsy-0.5.6 pyjwt-2.8.0 requests-unixsocket-0.3.0 scikit-learn-1.4.2
simplejson-3.19.2 statsmodels-0.14.1 threadpoolctl-3.4.0 toml-0.10.2
urllib3-1.26.18 wrapt-1.16.0 yarl-1.9.4 it gives me that , so what so i do
now

Στις Τετ 10 Απρ 2024 στις 10:21 μ.μ., ο/η nikolas galyfianakis <
***@***.***> έγραψε:

**Comment by ssolson** [comment] 2024-04-10 19:26
It looks like the install it worked.

You can `cd examples` and run an ipython notebook example of your choosing.

We have a release planned that is only waiting on PR #302 so fix for the current release will be out shortly.

Please let me know if the current install of MHKiT is not working for you.

**Comment by nikg321** [comment] 2024-04-10 19:34
i still get the same erros using pip install in spyder

Στις Τετ 10 Απρ 2024 στις 10:26 μ.μ., ο/η ssolson ***@***.***>
έγραψε:

**Comment by ssolson** [comment] 2024-04-10 19:49
> Successfully installed NREL-rex-0.2.86 aiobotocore-2.5.0 aiofiles-23.2.1 aiohttp-3.8.5 aiohttp-cors-0.7.0 aioitertools-0.11.0 aiosignal-1.3.1 async-timeout-4.0.3 azure-core-1.30.1 azure-storage-blob-12.19.1 beautifulsoup4-4.12.3 botocore-1.29.76 bottleneck-1.3.8 fatpack-0.7.7 frozenlist-1.4.1 h5pyd-0.18.0 hsds-0.8.4 isodate-0.6.1 jmespath-1.0.1 joblib-1.4.0 lxml-5.2.1 mhkit-0.7.0 multidict-6.0.5 numcodecs-0.12.1 patsy-0.5.6 pyjwt-2.8.0 requests-unixsocket-0.3.0 scikit-learn-1.4.2 simplejson-3.19.2 statsmodels-0.14.1 threadpoolctl-3.4.0 toml-0.10.2 urllib3-1.26.18 wrapt-1.16.0 yarl-1.9.4 it gives me that , so what so i do now Στις Τετ 10 Απρ 2024 στις 10:21 μ.μ., ο/η nikolas galyfianakis < ***@***.***> έγραψε:

There is no error in the output you are showing me. I need more details on what you are doing to help you.

If you are saying that `pip install mhkit` does not work in Spyder that is because there is a bug we have already fixed in the `develop` branch that I had you install that showed the succesful output above. 
`pip install mhkit`  will work again once we do the full release in the next ~2 weeks.

I do not use (or recommend) Spyder and therefore cannot tell you exactly how to get MHKiT into your Spyder IDE. If you want to continue using Spyder I would recommend looking for instructions on how to install from git in Spyder and use the `develop` branch of MHKiT.

I would recommend doing python development in VS Code. Within the terminal of VS Code you could install the `develop` brnach exactly as I had you do it before.

**Comment by nikg321** [comment] 2024-04-10 19:57
Great!

Στις Τετ 10 Απρ 2024, 10:49 μ.μ. ο χρήστης ssolson ***@***.***>
έγραψε:

**Comment by ssolson** [comment] 2024-04-10 20:05
@nikg321 thanks for bringing this to our attention and I apologize for the inconvenience.

We are working to get the new release out as soon as possible.

**Comment by ssolson** [comment] 2024-04-24 19:01
#307 will fix this issue once merged and a new release is tagged.

**Comment by nikg321** [comment] 2024-04-24 20:35
Ok, thanks for the update.

Στις Τετ 24 Απρ 2024, 10:01 μ.μ. ο χρήστης ssolson ***@***.***>
έγραψε:

**Comment by ssolson** [comment] 2024-05-14 13:39
@nikg321 MHKiT v0.8.0 was released last week and you should be able to install via pip again. 

Thank you for your interest in MHKiT and let us know if there are any more issues.

**Closed by ssolson** 2024-05-14 13:39 UTC
Labels: Clean Up
