### ISSUE TITLE
hdf5 headers not found

### ISSUE THREAD

**Issue by nikg321** [MHKiT-Software/MHKiT-Python#304] opened 2024-04-09 09:52 UTC
### Describe the bug:
hdf5 headers not found
### To Reproduce:
Provide a minimal working example that reproduces the error. 

**Minimal working example:** A minimal working example is a collection of source code and other data files which allow a bug or problem to be demonstrated and reproduced. The important feature of a minimal working example is that **it is as small and as simple as possible**, such that it is just sufficient to demonstrate the problem, but without any additional complexity or dependencies which will make resolution harder.

### Desktop (please complete the following information):
 - MHKiT Version: [e.g. 0.4.0]

**Comment by ssolson** [comment] 2024-04-09 13:32
Duplicate of #303

**Closed by ssolson** 2024-04-09 13:32 UTC
